### ISSUE TITLE
Graded Assignment 1 is confusing to run

### ISSUE THREAD

**Issue by kmonahan** [LaunchCodeEducation/intro-to-web-dev-curriculum#116]
Graded Assignment 1, Part 1 is one of the first times the learners encounter the unit test setup. In order to test their code as they go, they need to run `node index.js`, not `node candidate-testing.js`, even though for other exercises and studios so far, they're generally running the same file they're working on. This is not called out clearly in the instructions and leads learners to think their code isn't working because they're not seeing output in the console. There is guidance on how to run the automated tests but not on how to run their code themselves. I think this should be highlighted in project instructions and/or the instructions for all three parts of graded assignment 1.

**Comment by kihong017** [comment]
To add on to KJ's comment, we should be more specific on what the acceptance criterias are.
Right now, it just looks like the learners are only required to run `npm test` and pass all the test cases.

We should add something like:

In order to complete this assignment, you should do the followings:
- Running the test
	- npm test
- Running the program
	- node index.js

**Comment by jwoolbright23** [comment]
Added some instructions to book to alleviate the above issues!
